### PR TITLE
Allow fixing global configuration if it's invalid

### PR DESCRIPTION
**Pull request by timja**
Fixes https://github.com/jenkinsci/azure-keyvault-plugin/issues/47

If the credential used for the CredentialProvider was invalid it would cause a failure trying to lookup the credential and prevent you changing it,

I've changed it to log the failure and return empty

I've also added a test connection button to make errors less likely to happen

Fixes https://github.com/jenkinsci/azure-keyvault-plugin/issues/41

### CODE REVIEW

**Comment by jaheikki** [comment]
Is this correction included in version azure-keyvault:1.8, with 1.8 I can now see the 'test connection button'?

However the plugin v. 1.8 still crashes and I cannot find any way to change the non-working Credential ID. I also tried to "disable the credential provider" as you mentioned in https://github.com/jenkinsci/azure-keyvault-plugin/issues/47. 

Don't know if did the disable right (see figure)? At least I cannot find any " Azure KeyVault credential provider"...

image

**Comment by timja** [comment]
@jaheikki inside the providers dropdown you need to change it from all available,

hmm I'll check closer maybe I missed something

**Comment by jaheikki** [comment]
I tried to test your fix, maybe it was not available in version 1.8? Don't actually know what 'Merged' means... I configured non-working service principal on purpose and I got those exceptions back. However this time I couldn't solve those exceptions by any way. So needed remove this plugin since it disabled our 'live jenkins' totally...

**Comment by jaheikki** [comment]
The uninstalling of plugin will not uninstall configurations, so next time I re-install the plugin It will not work since it get's the old corrupted configuration back. Is there a way to delete the corrupted configurations from disk?

**Comment by timja** [comment]
> The uninstalling of plugin will not uninstall configurations, so next time I re-install the plugin It will not work since it get's the old corrupted configuration back. Is there a way to delete the corrupted configurations from disk?

Delete:
org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultGlobalConfiguration.xml

I've opened another PR which should hopefully fix your issue
https://github.com/jenkinsci/azure-keyvault-plugin/pull/52

Would you be able to test it?
https://ci.jenkins.io/job/Plugins/job/azure-keyvault-plugin/job/PR-52/1/artifact/org/jenkins-ci/plugins/azure-keyvault/1.9-rc96.48f059fda0a3/azure-keyvault-1.9-rc96.48f059fda0a3.hpi

**Comment by jaheikki** [comment]
Probably I can, should this fix the problem (despite the old configuration in xml) or should I delete the org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultGlobalConfiguration.xml first?

**Comment by jaheikki** [comment]
So I should just copy the .hpi to /var/lib/jenkins/plugins dir & restart jenkins?

**Comment by timja** [comment]
> So I should just copy the .hpi to /var/lib/jenkins/plugins dir & restart jenkins?

Yes that will work, or you can upload it from the advanced pane in the manage plugins section

**Comment by jaheikki** [comment]
Now I have the test version of plugin (did not delete the xml) and the problem is the same, it crashes:

image

**Comment by jaheikki** [comment]
So maybe I will delete the xml then...

**Comment by timja** [comment]
> So maybe I will delete the xml then...

That's different to what was reported in the other issue, taking a look anyway

**Comment by timja** [comment]
I've configured it locally with an invalid client secret and pushed a fix for that, a new build should be available in ~10-15 minutes

**Comment by jaheikki** [comment]
The test result of your current test plugin was, that it cannot solve the problem in case there's this old "corrupted" information in org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultGlobalConfiguration.xml. 
However problem get's fixed by deleting this xml, after that I'm able to select new Credential ID.

**Comment by timja** [comment]
New build if you want to try it:
https://ci.jenkins.io/job/Plugins/job/azure-keyvault-plugin/job/PR-52/2/artifact/org/jenkins-ci/plugins/azure-keyvault/1.9-rc97.2edf57eb3fde/azure-keyvault-1.9-rc97.2edf57eb3fde.hpi

**Comment by jaheikki** [comment]
Yes I will try it.

**Comment by jaheikki** [comment]
I can confirm now that this test version works fine! :) So even if I configure and save wrong service principal I can correct situation by using drop down menu. I hope your solutions covers all exceptions, meaning the drop down should work whatever problem there is with a selected service principal defined in Credentials ID field.  Will you now publish official version of the plugin? Will it be the v.1.9?

**Comment by timja** [comment]
> I can confirm now that this test version works fine! :) So even if I configure and save wrong service principal I can correct situation by using drop down menu. I hope your solutions covers all exceptions, meaning the drop down should work whatever problem there is with a selected service principal defined in Credentials ID field. Will you now publish official version of the plugin? Will it be the v.1.9?

Yes doing that now

**Comment by jaheikki** [comment]
Thanks a lot! :)

**Pull request merged**
